apiVersion: audit.k8s.io/v1 # This is required.
kind: Policy
# Don't generate audit events for all requests in RequestReceived stage.
omitStages:
  - "RequestReceived"
rules:
  # Log pod changes at RequestResponse level
  - level: RequestResponse
    resources:
    - group: ""
      resources: ["namespaces"]
  # Log "pods/log", "pods/status" at Metadata level
  - level: Request
    resources:
    - group: ""
      resources: ["pods", "services"]
    namespaces: ["web"]  
  - level: Metadata
    resources:
    - group: ""
      resources: ["secrets"]
  - level: Metadata
    omitStages:
      - "RequestReceived"
