Create a new secret in the larry namespace called moe.

Provide fields called username and password and store the following username and password credentials in the Secret:

username dbuser
password A83MaeKoz

echo -n 'dbuser' | base64
echo -n 'A83MaeKoz' | base64


apiVersion: v1
kind: Secret
metadata:
  name: moe
  namespace: larry
type: Opaque
data:
  username: ZGJ1c2Vy
  password: QTgzTWFlS296
