apiVersion: v1
kind: ServiceAccount
metadata:
  name: pod-monitor
  namespace: auth
automountServiceAccountToken: false

apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: auth
  name: pod-monitor
rules:
- apiGroups: [""] # "" indicates the core API group
  resources: ["pods"]
  verbs: ["get","list"]

apiVersion: rbac.authorization.k8s.io/v1
# This role binding allows "jane" to read pods in the "default" namespace.
# You need to already have a Role named "pod-reader" in that namespace.
kind: RoleBinding
metadata:
  name: read-pods
  namespace: auth
subjects:
# You can specify more than one "subject"
- kind: ServiceAccount
  name: pod-monitor # "name" is case sensitive
  apiGroup: ""
roleRef:
  # "roleRef" specifies the binding to a Role / ClusterRole
  kind: Role #this must be Role or ClusterRole
  name: pod-monitor # this must match the name of the Role or ClusterRole you wish to bind to
  apiGroup: ""

apiVersion: v1
kind: ServiceAccount
metadata:
  name: svc-monitor
  namespace: auth
automountServiceAccountToken: false

apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: auth
  name: svc
rules:
- apiGroups: [""] # "" indicates the core API group
  resources: ["services","endpoints"]
  verbs: ["get","list"]

apiVersion: rbac.authorization.k8s.io/v1
# This role binding allows "jane" to read pods in the "default" namespace.
# You need to already have a Role named "pod-reader" in that namespace.
kind: RoleBinding
metadata:
  name: read-svc
  namespace: auth
subjects:
# You can specify more than one "subject"
- kind: ServiceAccount
  name: svc-monitor # "name" is case sensitive
  apiGroup: ""
roleRef:
  # "roleRef" specifies the binding to a Role / ClusterRole
  kind: Role #this must be Role or ClusterRole
  name: svc # this must match the name of the Role or ClusterRole you wish to bind to
  apiGroup: ""