apiVersion: v1
kind: Secret
metadata:
  name: secret-tls
  namespace: accounts
type: kubernetes.io/tls
data:
  # the data is abbreviated in this example
  tls.crt: |
    LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURFVENDQWZtZ0F3SUJBZ0lVYWpRVUpKYzNo
    NkR1WkJ3QlYrOXYvVklpNStJd0RRWUpLb1pJaHZjTkFRRUwKQlFBd0Z6RVZNQk1HQTFVRUF3d01Z
    V05qYjNWdWRITXVjM1pqTUNBWERUSXlNRGd6TURFMU16UXlPVm9ZRHpJdwpOVEF3TVRFMU1UVXpO
    REk1V2pBWE1SVXdFd1lEVlFRRERBeGhZMk52ZFc1MGN5NXpkbU13Z2dFaU1BMEdDU3FHClNJYjNE
    UUVCQVFVQUE0SUJEd0F3Z2dFS0FvSUJBUURvckx6ZWpxR1VyRFo0U2x4OHh0emdXeFB5dnozVkpN
    QVEKTVBpMnNvY0dzUFUydXNBSGtoWkhUcDRhbG56b3BNSDBjNUFVUUdtZ0psbytraGFoNVJaTG5W
    VG1JdHB3WWZOegp3Z1A4TnMzdlFVRjBLbFVpdlhzKzM2dFhiQnNYUSs5enRYa09wek9FdDdzR1pk
    aXd4Qzd1dmtYT0NOdGtWQXZ6CkF1dmF4ZW1kRGdienRQSFoxbjlLQVNHdmp1ZGRjcGNtcm44d3Ni
    WjVPWnlKcElrb3lNTG13Smd1eTJpNTduaUUKV0JnRlBPMnlMcHcyME1DRUNNMUw2RERSZUM3OUNK
    cW9BbzZHRzFvM2tUZytULzZlRnhOZzFITTM2Q0kvNWhTNwpZVkJxczh0TlNBNjlkVFcydVRUbE5y
    QUllaDRhUGRzdlpFQUc2U1BxMmV2dUJVaW55cTZsQWdNQkFBR2pVekJSCk1CMEdBMVVkRGdRV0JC
    VDVDTm9Eb3Z1d214NkhsWXRmRDNyQWtwdUE5akFmQmdOVkhTTUVHREFXZ0JUNUNOb0QKb3Z1d214
    NkhsWXRmRDNyQWtwdUE5akFQQmdOVkhSTUJBZjhFQlRBREFRSC9NQTBHQ1NxR1NJYjNEUUVCQ3dV
    QQpBNElCQVFCWlhmUkxjQW9DMTh6NkpuR3ZBb0Q5dVJWdWMzSmozVUFWTTdoYnpPZC9lS3AyUDha
    Q3VZckFPM2JaCmlxZ0xTQXk3U1owakR6N1hSK0ppTjhyQlZkeXpzN1FsZnFoTGhRU1BTeFd3RHRX
    aWRIRGcwaE5Ha29iN2RqMUkKVTE2ZkIvRVBBRHBlRDFwZHZuS1lPYnVKNWhMc21mSk5XUWVOQ3Zy
    TExSYjJQMTJFdG9yeUh0dTZId3o4SFQ4Qwphbk8xVnpYV3N3eHN6MktkRnVJNENXbElsYkhlZWY4
    c0NkcFZUTGQvWUZQV1hjckpVc1ljNGhoeUtVM1ZPNUVOClN5eGZMcG5rUDJycXR1YnhvVTVJcTE2
    bFRjR0pUWGlJRXV5elFpNnJXOTJSK0VCWlBZVE9CTEJ1Qm9UTndMNk8KUWNtRXcvS1BzSmhBcFJq
    ZnpicVJKY2Vid0JUegotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg==
  tls.key: |
    LS0tLS1CRUdJTiBSU0EgUFJJVkFURSBLRVktLS0tLQpNSUlFcFFJQkFBS0NBUUVBNkt5ODNvNmhs
    S3cyZUVwY2ZNYmM0RnNUOHI4OTFTVEFFREQ0dHJLSEJyRDFOcnJBCkI1SVdSMDZlR3BaODZLVEI5
    SE9RRkVCcG9DWmFQcElXb2VVV1M1MVU1aUxhY0dIemM4SUQvRGJONzBGQmRDcFYKSXIxN1B0K3JW
    MndiRjBQdmM3VjVEcWN6aExlN0JtWFlzTVF1N3I1RnpnamJaRlFMOHdMcjJzWHBuUTRHODdUeAoy
    ZFovU2dFaHI0N25YWEtYSnE1L01MRzJlVG1jaWFTSktNakM1c0NZTHN0b3VlNTRoRmdZQlR6dHNp
    NmNOdERBCmhBak5TK2d3MFhndS9RaWFxQUtPaGh0YU41RTRQay8rbmhjVFlOUnpOK2dpUCtZVXUy
    RlFhclBMVFVnT3ZYVTEKdHJrMDVUYXdDSG9lR2ozYkwyUkFCdWtqNnRucjdnVklwOHF1cFFJREFR
    QUJBb0lCQVFDc0hod1pCcW5Bc1NRYQpGK2dTNVlpKzdxRHpFVVZNUnNOTk51ekZPWXRwQjc1ZG5n
    Z3ZrWUdwZmg2MnpGdmFQUWE5TGorR3U1OW5PUGZKCkVZaHNlbXJqeEo3cEh4ODN3ejIwZy9FdXdk
    dlZBUkRLUGdaOGpHNS9ORFlybFd6MDZPeFpUQVVoTWM2S2Z0OTYKL0J3dnB2Q1E2Mi8zMmRWeGdq
    clVxWFNQZ1pndTlLaFhLMGN2eitKQWNtUkphOWI4ak5GaS9TY1Q1SzQxMGEvdAp4UVhKNkR0N3ps
    MVRKL2Z1Q1VKcUpBTUE3VkhDcE83a21BaXBOZHN1aHNjRmlMM285RzU1V0lONlVidTQwQmd5Cmhw
    TmZqZGdHWWFXaEVCWFM3bjlOazg3MW5YamlwY2VLSkFSMUd4R2JXNmgyOWNoSy9md1REYms1cmZY
    Rldma2MKUDlNU3IraUJBb0dCQVBZcGYwaXIyaTZhMUpjZ2MzY3ZJYzZPci9oZ0QraFA2ekVqT05r
    eCtGMi8vdjJHdzJyYQpiSGI1QmQwOGhyWlk4Q2o2Z1hEeWRVWDlkQ1JaTi9DSGkvckY4d3ZWMTBL
    aVZwbWhOWmFBYXJPeCtxZlNqRkRoCjVyUmZlR1BoMjVSMVIvQzFLZlBLaHRzV3gxTUtobGY1eW94
    aDYxdndCcVlwKzZqRVFJaDZ5bnpmQW9HQkFQSDUKUUNWblVPQ1EvTElmS01rRXVpYk1vMlVaT3VN
    a3ZwYi92YlQwWDlQNm1lNUt1bDlzNzJxTG9BNytNUGEzRTBTMwpkUmQyTmJraHFnSHRtMDNwVHVD
    SFNIajFHTGUzbzB1aDEwcXVldWh5anpaWUVGVlNlL3d0Szl0ckNmeGdpblNpCks4QXZTSE9LbXZC
    cEY4VWIydHAwNEdpeWVYbVlrWTRTVVcxeXhjRDdBb0dBU0tSK1YyZS9memxadXk5c1k2T1oKQ21l
    NUxrYks2dmVLcEhtTWNTdjU2MUNaWXgrOTAyNlp5NUk1Vk14anhMUUNTMVdCbFY4M2xHdnpOamJO
    OTBGSQo0YnhBdVNGbDROZ2ZUajd3blhWUUI2OWlGTnhoWkEwR0UveUlmcEZNUjBkRTc1Zkd4WmJp
    clF6UHpZV3hsNHl6ClpUSVFUcFZLb1FhS3FZY2d0Q1hvVTJrQ2dZRUFyT2FLZEcrZnRlZEQrVThV
    aUpidElQNUdudDNwV3hjTmJMNHUKNHhkZlJnd2lZOGhYNWdua0JZRGhqUFVMTGE5aGdFK0t4b244
    RjE0N3FZY0wyeDhqOG9JWVFmMzRmSVltazh1QQpGK2dYQVBPaTY1VC9qc2dTdWYzWkFiODVjbkhW
    WFVQbitUcVFEYWR6ME9kM1Nhdit0T3lnMFk3K0Irb0J6Nys5CkdYVFNZM01DZ1lFQWp5Z29TUWQv
    OFYvODhJRXRlQy9kWFBuN0tqNDJJcC9qVm1vc21CZ3ZSYU1ZK29EZTcyVysKeHhYU0psTk9yaEx6
    VDBiRjlxRTRqK3JNRUM4WWJQWEJMNFlrU0RUYkhLTnN3dEdUOGFRNkswcStZcmF6RnZndAovTlp4
    dE1KRU5LVU94ODI1dVhGQVp2d0xCMG52MEpBVzZPeDBxZ2s3WjJSdnBnRDhGbkc1UnJNPQotLS0t
    LUVORCBSU0EgUFJJVkFURSBLRVktLS0tLQo=